discovery:
  jobs:

  - type: lambda
    regions:
      - eu-west-1
    addUntagged: True
    period: 300
    length: 300
    searchTags:
      - Key: type
        Value: ^(easteregg|k8s)$
    metrics:
      - name: Invocations
        statistics:
          - Sum
