---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.yace.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.yace.aws.account_id }}:role/{{ .Values.yace.aws.role_name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: yace
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yace
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: yace
subjects:
  - kind: ServiceAccount
    name: {{ .Values.yace.serviceAccount }}
    namespace: {{ .Release.Namespace }}
